.\" Generated with the mancreator
.\" kai gonzalez 2021
.
.TH "MAN\.MAN" "1" "August 2021" "1.0" "Kai's Command Essentials Manual"
.
.SH "NAME"
\fBman\.man\fR \- Python3 Library for Compressing, Decompressing, and reading Unix manual pages\.
.
.SH "SYNOPSIS"
import \fIman\.man\fR as \fIman\fR
.
.P
\fIman\.compress(page)\fR
.
.P
\fIman\.decompress(page)\fR
.
.P
\fIman\.read_page(page)\fR
.
.SH "DESCRIPTION"
\fIman\fR is a python3 library for simply reading, compressing, or getting native data about Unix manual pages\.
.
.P
\fIman\fR is 100% native and uses no external APIs other than the Python API\.
.
.P
\fIman\fR is also \fBOpen Source\fR, using one of the most liberal licenses (MIT)\.
.
.SH "OPTIONS"
.
.nf

**db**
    Sets DEBUG to value\. Only valid in Python3 Functions\.
**page**
    The page to look for\.
**abspath**
    The absolute path of something\.
.
.fi

